---
argument_specs:
  main:
    short_description: Create or deactivate a Synology account
    options:
      accounts_do_list:
        type: bool
        default: false
      accounts_do_create:
        type: bool
        default: false
      accounts_do_disable_samba:
        type: bool
        default: false
      accounts_do_delete:
        type: bool
        default: false
      account:
        type: dict
        required: true
        options:
          username: {type: str, required: true}
          password: {type: str, required: false, no_log: true}
          groups:   {type: list, elements: str, required: false}
          create_home: {type: bool, default: true}