---
  - name: Include list
    import_tasks: list.yml
    when: action | default('list') == 'list'

  - name: Include configure
    import_tasks: configure_ipv4.yml
    when: action | default('list') == 'configure'