block:
  - name: interface object is set and interface name is defined
    ansible.builtin.assert:
      that:
        - interface is defined
        - interface.iface is defined
        - interface.iface | length > 0
      fail_msg: "The interface object must be set and interface name must be defined"

  - name: no static fields if dhcp
    ansible.builtin.assert:
      that:
        - not (interface.dhcp | default(false)) or
          (
            (interface.ip | default(None)) is none and
            (interface.mask | default(None)) is none
          )
      fail_msg: "When dhcp is true, no address/netmask"

  - name: address and netmask are mandatory when static configuration
    ansible.builtin.assert:
      that:
        - (interface.dhcp | default(false)) or
          (interface.ip is not none and interface.mask is not none)
      fail_msg: "When static configuration, 'address' and 'netmask' are required"

when: action == 'config'